name: minimo_video
description: "minimo (video) - video compression app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  v_video_compressor: ^2.0.0
  flutter_bloc: ^9.1.1
  gal: ^2.3.2
  flutter_svg: ^2.3.0
  flutter_launcher_icons: ^0.14.4
  auto_route: ^11.1.0
  auto_route_generator: ^10.5.0
  build_runner: ^2.15.0
  intl_utils: ^2.8.11
  path_provider: ^2.1.5
  path: ^1.9.1
  reel_text: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  image_path_ios: "assets/logo/logo.png"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_foreground: "assets/logo/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/

  fonts:
    - family: Pangolin
      fonts:
        - asset: assets/fonts/Pangolin-Regular.ttf
flutter_intl:
  enabled: true
